# 220503 JAVA

## 객체 지향의 4대 특성

1. 캡슐화 (Encapsulation)와 정보 은닉(Information Hiding)
    - 변수와 메서드를 하나로 묶는 패키징 형태
    - setter, getter를 통해 정보 field값을 수정하는 캡슐화를 통해 정보은닉
    - 접근 제어자 사용 (public, private, protected, default)
2. 상속 - 재사용성(Reusable) + 확장
    - 코드의 중복을 제거 -> 재사용

3. 추상화
    - 객체 혹은 클래스를 모델링할 때 개별에서 하나의 '추상화(분류)'를 만든다.

4. 다형성
    - 다양한 형태를 띌 수 있는 성질
    - 참조변수의 타입을 인터페이스 타입으로 사용하여 코드의 변경이 줄어들고,   
      클래스간 직접적인 관계(결합도가 높은 상태)에서 간접적인 관계(낮은 결합도, 느슨한 결합)로 만든다.

> 객체지향 4대 특성을 활용해 코드의 중복 제거, 관리를 용이(유지보수)하게 한다

## 예외 처리 (Exception Handling)
- 내가 작성한 코드가 실행 도중에 어떤 원인에 의해 오작동(예상과는 다르게 작동)하거나   
  비정상적으로(갑자기) 종료가 되는 경우가 있다
- 이러한 결과를 초래한 원인을 프로그램 오류라고 함
- 원인
    1. 컴파일 오류 (compile-time error) : 코드의 실행 전에 발생하는 빨간 밑 줄
    2. 런타임 오류 (runtime error) : 코드 실행과정에서 발생하는 오류
    3. 논리적 오류 (logical error)

### 컴파일 오류
- 소스 코드의 컴파일 과정에서 발생하는 오류. (ex. syntax error)

### 런타임 오류
- 문법을 맞았으나, 실행 과정에서 발견(확인)되는 오류

### 논리적 오류
- 문법도 맞고 실행과정에서 오류도 없지만 논리가 틀림
    - 나이변수에 음수값같은 경우

> 자바에서는 실행 시(runtime)발생할 수 있는 프로그램 오류를 '에러 error'와 '예외 exception'로 분류

### 에러(Error)
- 시스템 레벨에서 발생. 복구가 어렵고 개발자가 제어하기 어려움.
- 메모리 부족, 스택오버플로 등

### 예외 (Exception)
- 개발자의 코드에서 발생. 예방(대처) 가능
- 발생하더라도 수습될 수 있음. 에러에 비해 비교적 덜 심각.
    - NullPointerException, IndexOutOfBounds...
- 에러는 비정상적인 종료가 된다.

> 객체 위계
> - Object -> Throwable -> Exception -> Runtime Exception, IO Exception   
>                       -> Error -> OutofMemory Error,StackOverflow Error
> - Throwable 은 인터페이스. Exception과 Error는 implements 관계
> - Exception 클래스는 Throwable 인터페이스를 구현했기 때문에, 던질 수 있는 능력을 갖고 있다. 예외를 던진다.
> - Exception 을 상속(Extends)받는 (Runtime Exception 같은) 디테일한 예외.

### 발생한 예외의 처리 : try - catch
- 발생할 수 있는 예상치 못한 예외의 발생에 대처가 가능한 코드를 작성

```java
try {
    // 예외가 발생할 가능성이 보이는 코드를 작성
    Audio a = new Audio();
    Bts b = null;
    a.musicPlay(b); // 음악이 하나도 없는 상황 발생
} catch (LpEmptyException e1) { // LpEmptyException 클래스의 인스턴스 생성
    // Lp에 음악이 하나도 없을 때 처리하기 위한 코드 작성
    System.out.println(e1);
} catch (MusicDuplicateException e2) {
    // 같은 음악이 2개 이상 있을 때 처리 코드 작성
} catch (Exception e) {
    // 위 예외를 제외한 나머지 모든 예외를 잡고 싶을 때
}
```

```java
public class Ex2 {
	public static void main(String[] args) {
		int number = 100;
		int result = 0;
		
		// number 값을 랜덤값으로 나눈 결과 출력
		for (int i = 0; i < 10; i++) {
			try { // try block				
				result = number / (int)(Math.random() * 10);
				System.out.println(result);
			} catch (ArithmeticException exception) {
				System.out.println("0으로 나?눠?");
				exception.printStackTrace();
				System.out.println(exception.getMessage());
			}
		}
	}
}
```